# Generated by Django 5.0.1 on 2024-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'About Table',
            },
        ),
    ]
