# Generated by Django 5.0.1 on 2024-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Portfolio Table',
            },
        ),
    ]
