# Generated by Django 5.0.1 on 2024-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.ImageField(upload_to='news_images/')),
                ('news_heading', models.TextField()),
                ('news_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Latest News Table',
            },
        ),
    ]
